# SPDX-FileCopyrightText: Copyright DB Netz AG
# SPDX-License-Identifier: CC0-1.0

name: dbs-onboard-map-api CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Map-Service code including submodules recursively
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y cmake
        sudo apt-get install gcovr -y
        sudo apt-get install libgmock-dev libgtest-dev
        sudo apt-get install -y rapidjson-dev
        sudo apt-get install libcurl4-openssl-dev protobuf-compiler libprotobuf-dev libboost-all-dev -y --no-install-recommends --fix-missing

    - name: Build Map-Service sources
      run: ./build.sh -DCMAKE_BUILD_TYPE=Debug

    - name: Run Test
      run: |
        ${{github.workspace}}/build/map-service/tests/GoogleTestRunner


    - name: Generate Test Coverage
      run: |
        ${{github.workspace}}/scripts/code_coverage.sh

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ${{github.workspace}}/build/coverage/coverage.html

    - name: Upload coverage to GitHub
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: ${{github.workspace}}/build/coverage/*
