# SPDX-FileCopyrightText: Copyright DB Netz AG
# SPDX-License-Identifier: CC0-1.0

name: dbs-onboard-map-api CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '**'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout DBS Onboard API code including submodules recursively
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y cmake
        sudo apt-get install -y gcovr
        sudo apt-get install libgmock-dev libgtest-dev
        sudo apt-get install -y rapidjson-dev
        sudo apt-get install -y doxygen
        sudo apt-get install libcurl4-openssl-dev protobuf-compiler libprotobuf-dev libboost-all-dev -y --no-install-recommends --fix-missing

    - name: Build DBS Onboard MAP API sources
      run: ./scripts/build.sh -DCMAKE_BUILD_TYPE=Debug

    - name: Run Test
      run: |
        ${{github.workspace}}/build/dbs-map-api/tests/GoogleTestRunner


    - name: Generate Test Coverage
      run: |
        ${{github.workspace}}/scripts/code_coverage.sh

    # - name: Upload coverage reports to Codecov
    #   uses: codecov/codecov-action@v3
    #   with:
    #     token: ${{ secrets.CODECOV_TOKEN }}
    #     file: ${{github.workspace}}/build/coverage/coverage.html
    #   env:
    #     CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ${{github.workspace}}/build/coverage/coverage.xml
        fail_ci_if_error: true

    - name: Upload coverage to GitHub as artifact
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: ${{github.workspace}}/build/coverage/*

    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        folder: build/docs/html
        branch: gh-pages