# SPDX-FileCopyrightText: Copyright DB Netz AG
# SPDX-License-Identifier: CC0-1.0

name: Map-Service CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Map-Service code including submodules recursively
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y cmake
        sudo apt-get install gcovr -y
        sudo apt-get install libgmock-dev libgtest-dev
        sudo apt-get install -y rapidjson-dev
        sudo apt-get install libcurl4-openssl-dev protobuf-compiler libprotobuf-dev libboost-all-dev -y --no-install-recommends --fix-missing

    - name: Build Map-Service sources
      run: ./build.sh -DCMAKE_BUILD_TYPE=Debug

    - name: Run Test
      # working_directory: ${{github.workspace}}/build
      run: ./build/map-service/tests/GoogleTestRunner

    - name: Generate Test Coverage
      run: |
        cd ./build
        gcovr -r .. --html --html-details -o coverage.html
