# SPDX-FileCopyrightText: Copyright DB Netz AG
# SPDX-License-Identifier: CC0-1.0

name: dbs-onboard-map-api CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '**'

env:
  IS_MAIN_BRANCH: ${{ github.ref == 'refs/heads/main' }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout DBS Onboard API code including submodules recursively
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y cmake
        sudo apt-get install -y gcovr
        sudo apt-get install libgmock-dev libgtest-dev
        sudo apt-get install -y rapidjson-dev
        sudo apt-get install -y doxygen
        sudo apt-get install libcurl4-openssl-dev protobuf-compiler libprotobuf-dev libboost-all-dev -y --no-install-recommends --fix-missing

    - name: Build DBS Onboard MAP API sources
      run: ./scripts/build.sh -DCMAKE_BUILD_TYPE=Debug

    - name: Set up Python
      uses: actions/setup-python@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    # - name: Run Mock Map Server
    #   run: |
    #     nohup python3 ${{github.workspace}}/dbs-map-mock-server/dbs-map-mock-server.py &

    - name: Run Test
      run: |
        nohup python3 ${{github.workspace}}/dbs-map-mock-server/dbs-map-mock-server.py &
        sleep 5
        ${{github.workspace}}/build/dbs-map-api/tests/GoogleTestRunner

    - name: Generate Test Coverage
      if: env.IS_MAIN_BRANCH == 'true'
      run: |
        ${{github.workspace}}/scripts/code_coverage.sh

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      if: env.IS_MAIN_BRANCH == 'true'
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ${{github.workspace}}/build/coverage/coverage.xml
        fail_ci_if_error: true

    # Coverage is already uploaded to Codecov
    # - name: Upload coverage to GitHub as artifact
    #   uses: actions/upload-artifact@v2
    #   if: env.IS_MAIN_BRANCH == 'true'
    #   with:
    #     name: coverage
    #     path: ${{github.workspace}}/build/coverage/*
