# SPDX-FileCopyrightText: Copyright DB Netz AG
# SPDX-License-Identifier: CC0-1.0

name: Build and Push Map Mock Server Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'
    paths:
      - 'dbs-map-mock-server/**'
env:
  IMAGE_NAME: dbs-map-mock-server
  VERSION: 1.0.0
#   CR_PAT: ${{ secrets.CR_PAT }}

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3

    #   - name: Log in to GitHub Container Registry
    #     run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Login to github container registry
        uses: docker/login-action@v2
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Log in to GitHub Container Registry
      #   run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker Image
        run: docker build -t ${{ env.IMAGE_NAME }} ./dbs-map-mock-server

      - name: Tag Docker Image
        # run: docker tag ${{ env.IMAGE_NAME }} ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
        run: docker tag ${{ env.IMAGE_NAME }} ghcr.io/dsd-dbs/dbs-onboard-map-api/${{ env.IMAGE_NAME }}:${{ env.VERSION }}

      # - name: Push Docker Image
      #   run: docker push ghcr.io/dsd-dbs/dbs-onboard-map-api/${{ env.IMAGE_NAME }}:${{ env.VERSION }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v3
        with:
          context: ${{github.workspace}}/dbs-map-mock-server
          tags: ghcr.io/dsd-dbs/dbs-onboard-map-api/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          # labels: git-short-sha=${{ steps.tag.outputs.sha }}
          push: true

    #   - name: Tag Docker Image
    #     run: docker tag ${{ env.IMAGE_NAME }} ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}

    #   - name: Push Docker Image
    #     run: docker push ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
