# SPDX-FileCopyrightText: Copyright DB Netz AG
# SPDX-License-Identifier: CC0-1.0

name: Build and Push Map Mock Server Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'
    paths:
      - 'dbs-map-mock-server/**'
env:
  IMAGE_NAME: dbs-map-mock-server
  VERSION: 1.0.0
  REGISTRY: ghcr.io
  # ${{ github.repository_owner }}
  REPOSITORY_OWNER: dsd-dbs
  # ${{ github.repository_owner }}
  REPOSITORY: dsd-dbs/dbs-onboard-map-api

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: Login to github container registry
        uses: docker/login-action@v2
        with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v3
        with:
          context: ${{github.workspace}}/${{ env.IMAGE_NAME }}
          tags: ${{ env.IMAGE_NAME }} ${{ env.REGISTRY }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          # labels: git-short-sha=${{ steps.tag.outputs.sha }}
          push: true
