# SPDX-FileCopyrightText: Copyright DB Netz AG
# SPDX-License-Identifier: CC0-1.0

name: Build and Push Map Mock Server Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'
    paths:
      - 'dbs-map-mock-server/**'
env:
  IMAGE_NAME: dbs-map-mock-server
  REGISTRY: ghcr.io
  # ${{ github.repository }}
  REPOSITORY: dsd-dbs/dbs-onboard-map-api

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: Login to github container registry
        uses: docker/login-action@v2
        with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get the branch name
        id: get_branch
        run: echo ::set-output name=BRANCH::${GITHUB_REF#refs/heads/}

      - name: Get the short SHA
        id: get_sha
        run: echo ::set-output name=SHA::$(git rev-parse --short HEAD)

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v3
        with:
          context: ${{github.workspace}}/${{ env.IMAGE_NAME }}
          tags: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ steps.get_branch.outputs.BRANCH }}
          labels: git-short-sha=${{ steps.get_sha.outputs.sha }}
          push: true
